[build]
  publish = "public"
  command = "mkdir -p public && cp -r templates/* public/ && cp *.html public/"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200
  force = true
