# Basic Netlify configuration for a React project
[build]
  command = "CI= npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD -- . ':(exclude)requirements.txt' ':(exclude)setup.py' ':(exclude)Procfile' ':(exclude)akrunanalytics/'"

# Redirect API requests to your Heroku backend
[[redirects]]
  from = "/api/*"
  to = "https://api.akrunanalyticscorp.com/api/:splat"
  status = 200
  force = true

# Support for single-page applications with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
