[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://api.akrunanalyticscorp.com/api/:splat"
  status = 200
  force = true

# This ensures that React Router works properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
