[build]
  command = "npm run build"
  publish = "dist"

[build.processing]
  skip_processing = true

# Redirect API requests to your Heroku backend
[[redirects]]
  from = "/api/*"
  to = "https://api.akrunanalyticscorp.com/api/:splat"
  status = 200
  force = true

# Support for single-page applications with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
