# Simple build configuration
[build]
  command = "cp netlify-frontend-package.json package.json && npm install --no-audit --no-fund && npm run build"
  publish = "dist"
  ignore_requirements_txt = true
  environment = { NODE_VERSION = "20", PYTHON_ENABLED = "false" }
  functions = "netlify/functions"

# Redirect API requests to the backend
[[redirects]]
  from = "/api/*"
  to = "https://api.akrunanalyticscorp.com/api/:splat"
  status = 200
  force = true

# Support SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
