# Basic Netlify configuration for a React project
[build]
  command = "CI= npm run build"
  publish = "dist"
  # Skip installing python dependencies
  environment = { SKIP_PYTHON_REQUIREMENTS = "true", PYTHON_VERSION = "off", NODE_VERSION = "18" }

# Redirect API requests to your Heroku backend
[[redirects]]
  from = "/api/*"
  to = "https://api.akrunanalyticscorp.com/api/:splat"
  status = 200
  force = true

# Support for single-page applications with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
